#
#////////////////////////////////////
#         DeathLogManager
#////////////////////////////////////
#


#[DefaultType]
#ユーザーが何も設定していない標準状態のデフォルトの受け取り方です。
#<設定可能な値>
#* each
#* near
#* self
#* simple
DefaultType: each